# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(1070, 475)
        self.gridLayout = QtWidgets.QGridLayout(form)
        self.gridLayout.setObjectName("gridLayout")
        self.homeButton = QtWidgets.QToolButton(form)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 1, 1, 1, 1)
        self.removeButton = QtWidgets.QPushButton(form)
        self.removeButton.setEnabled(False)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 3, 4, 1, 1)
        self.newFolderButton = QtWidgets.QPushButton(form)
        self.newFolderButton.setObjectName("newFolderButton")
        self.gridLayout.addWidget(self.newFolderButton, 3, 6, 1, 1)
        self.directoryLabel = QtWidgets.QLineEdit(form)
        self.directoryLabel.setObjectName("directoryLabel")
        self.gridLayout.addWidget(self.directoryLabel, 0, 3, 1, 4)
        self.execButton = QtWidgets.QToolButton(form)
        self.execButton.setObjectName("execButton")
        self.gridLayout.addWidget(self.execButton, 1, 7, 1, 1)
        self.goButton = QtWidgets.QToolButton(form)
        self.goButton.setObjectName("goButton")
        self.gridLayout.addWidget(self.goButton, 0, 7, 1, 1)
        self.baseTree = QtWidgets.QTreeWidget(form)
        self.baseTree.setObjectName("baseTree")
        self.baseTree.header().setDefaultSectionSize(150)
        self.baseTree.header().setMinimumSectionSize(75)
        self.gridLayout.addWidget(self.baseTree, 2, 0, 1, 8)
        self.backButton = QtWidgets.QToolButton(form)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 1, 0, 1, 1)
        self.redoButton = QtWidgets.QToolButton(form)
        self.redoButton.setObjectName("redoButton")
        self.gridLayout.addWidget(self.redoButton, 1, 2, 1, 1)
        self.dirLabel = QtWidgets.QLabel(form)
        self.dirLabel.setObjectName("dirLabel")
        self.gridLayout.addWidget(self.dirLabel, 0, 0, 1, 3)
        self.commandArea = QtWidgets.QLineEdit(form)
        self.commandArea.setObjectName("commandArea")
        self.gridLayout.addWidget(self.commandArea, 1, 3, 1, 4)
        self.renameButton = QtWidgets.QPushButton(form)
        self.renameButton.setEnabled(False)
        self.renameButton.setObjectName("renameButton")
        self.gridLayout.addWidget(self.renameButton, 3, 3, 1, 1)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Primus Folder Manager 1.0"))
        self.homeButton.setText(_translate("form", "H"))
        self.removeButton.setText(_translate("form", "Remove"))
        self.newFolderButton.setText(_translate("form", "New folder"))
        self.execButton.setText(_translate("form", ">"))
        self.goButton.setText(_translate("form", ">"))
        self.baseTree.headerItem().setText(0, _translate("form", "Names"))
        self.baseTree.headerItem().setText(1, _translate("form", "Type"))
        self.baseTree.headerItem().setText(2, _translate("form", "Size"))
        self.baseTree.headerItem().setText(3, _translate("form", "Last Access"))
        self.baseTree.headerItem().setText(4, _translate("form", "Last Modification"))
        self.backButton.setText(_translate("form", "<"))
        self.redoButton.setText(_translate("form", ">"))
        self.dirLabel.setText(_translate("form", "Directory: "))
        self.renameButton.setText(_translate("form", "Rename"))
